### ISSUE TITLE
 BUG: IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by taariq** [VolumeFi/trading-bots#12]
When running
`$: poetry run python3.9 momentumscanner_techindicator.py uniswap_v3 6`

I get the error:
Traceback (most recent call last):
  File "/momentumscanner_techindicator.py", line 432, in <module>
    findbestreturn(
  File "/momentumscanner_techindicator.py", line 388, in findbestreturn
    hottoken = df.index[0]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5039, in __getitem__
    return getitem(key)
**IndexError: index 0 is out of bounds for axis 0 with size 0**

**Comment by fieldtheory123** [comment]
The cause has been found and it exists in multiple scripts. Looking for a good way to clean it up together.

**Comment by fieldtheory123** [comment]
This should fix it @taariq 
https://github.com/VolumeFi/trading-bots/pull/13
