### ISSUE TITLE
BUG: NameError: name 'querycoin' is not defined

### ISSUE THREAD

**Issue by taariq** [VolumeFi/trading-bots#6]
After the upgrade to poetry.

```
liquidity profile:
Traceback (most recent call last):
  File "/Users/taariqlewis/Projects/VolumeFi_Projects/trading-bots/MomentumScanner_intraday.py", line 357, in <module>
    findbestreturn(dex=str(sys.argv[1]), stoploss=0.05, profittaking=0.05, lag=lag)
  File "/Users/taariqlewis/Projects/VolumeFi_Projects/trading-bots/MomentumScanner_intraday.py", line 344, in findbestreturn
    findliquidity(hottoken, dex)
  File "/Users/taariqlewis/Projects/VolumeFi_Projects/trading-bots/MomentumScanner_intraday.py", line 253, in findliquidity
    re = querycoin(coin)
NameError: name 'querycoin' is not defined
```

**Comment by fieldtheory123** [comment]
I got this error too but apparently the issue starts even before that line. Some of the queries' urls are incorrect and the number of queries also increased significantly, presumable due to the incorrect urls. The error log contains a lot these failed queries:

`$ python MomentumScanner_intraday.py uniswap_v2 6`
`
Failed to fetch https://pro-api.coingecko.com/api/v3/coins/0?x_cg_pro_api_key=CG-tqNmJikUwRSqWbPkasz89dqj: <class 'asyncio.exceptions.TimeoutError'>
Failed to fetch https://pro-api.coingecko.com/api/v3/coins/0?x_cg_pro_api_key=CG-tqNmJikUwRSqWbPkasz89dqj: <class 'asyncio.exceptions.TimeoutError'>
Failed to fetch https://pro-api.coingecko.com/api/v3/coins/-?x_cg_pro_api_key=CG-tqNmJikUwRSqWbPkasz89dqj: <class 'asyncio.exceptions.TimeoutError'>
Failed to fetch https://pro-api.coingecko.com/api/v3/coins/t?x_cg_pro_api_key=CG-tqNmJikUwRSqWbPkasz89dqj: <class 'asyncio.exceptions.TimeoutError'>
Failed to fetch https://pro-api.coingecko.com/api/v3/coins/t?x_cg_pro_api_key=CG-tqNmJikUwRSqWbPkasz89dqj: <class 'asyncio.exceptions.TimeoutError'>
Failed to fetch https://pro-api.coingecko.com/api/v3/coins/c?x_cg_pro_api_key=CG-tqNmJikUwRSqWbPkasz89dqj: <class 'asyncio.exceptions.TimeoutError'>
Failed to fetch https://pro-api.coingecko.com/api/v3/coins/a?x_cg_pro_api_key=CG-tqNmJikUwRSqWbPkasz89dqj: <class 'asyncio.exceptions.TimeoutError'>
Failed to fetch https://pro-api.coingecko.com/api/v3/coins/r?x_cg_pro_ap
`

**Comment by fieldtheory123** [comment]
@measure-fi

**Comment by taariq** [comment]
Fixed.
